### ISSUE TITLE
Warnings due to deprecated linter, linter oprtion, name

### ISSUE THREAD

**Issue by talx-hub** [s-shpak/praktikum-golangci-lint#1]
`WARN [config_reader] The configuration option `linters.sloglint.context-only` is deprecated, please use `linters.sloglint.context`.`
`WARN The linter 'gomnd' is deprecated (since v1.58.0) due to: The linter has been renamed. Replaced by mnd.`
`WARN The linter 'execinquery' is deprecated (since v1.58.0) due to: The repository of the linter has been archived by the owner.`

**Comment by s-shpak** [comment]
Thank you for the report and for the fixes! I have merged them
